const en = {
  "home.nextAction": "Choose your next step",
"video.provenance":"AI video analysis \u00b7 paraphrases, not verified captions. Timestamps are approximate.",
"video.approximate":"Approximate \u00b7 AI video analysis",
"busy.video":"Analyzing video directly",

  "profile.simpleIntro": "Settings and how you like to learn.",
  "profile.tab.settings": "Settings",
  "profile.tab.teaching": "Teaching preferences",
  "profile.tab.memory": "Memory",
  "profile.languageSafe": "New explanations and memory updates use your preferred language. Existing conversations are preserved; the mentor can also use memory written in another language.",
  "profile.yourChoices": "Your choices",
  "profile.choicesHint": "Select the approaches you prefer. Blue pills are your choices; you can change them anytime.",
  "profile.custom": "Add your own preference",
  "profile.addPreference": "Add",
  "profile.mentorNotes": "Observations from conversations",
  "profile.mentorNotesHint": "Purple pills are observations recorded by the mentor, including earlier memory. They may depend on the topic. Your explicit choices and current request take priority. Remove anything that does not fit.",
  "profile.choice.0": "Step by step",
  "profile.choice.1": "Concrete examples",
  "profile.choice.2": "Code examples",
  "profile.choice.3": "Visual diagrams",
  "profile.choice.4": "Analogies",
  "profile.choice.5": "Short explanations",
  "profile.choice.6": "Technical depth",
  "profile.choice.7": "Optional practice questions",

  "home.yourLearning": "Your learning space",
  "home.otherTopic": "Another topic",
  "home.start": "What would you like to explore?",
  "home.startHint": "Choose a topic on the map or search above. Your conversations and learning goals will be here when you return.",
  "home.chooseTopic": "Choose a topic",
  "home.currentRecent": "Current topic · last conversation",
  "search.browse": "Search and explore",
  "search.topics": "Topics",
  "search.clusters": "Clusters",
  "search.hint": "Type to search, choose a topic, or explore a cluster.",
  "search.resultsHint": "Choose a result to open it.",
  "search.count": "{n} topics",
  "search.noClusters": "No matching clusters.",
  "search.clearCluster": "Clear cluster {name}",

  "journey.reviewRequest": "Can we briefly revisit this topic? Give me one short application question; I’ll decide whether I want to try it.",
  "journey.reviewStart": "Try a short review",
  "journey.cycle": "This route contains a prerequisite cycle. The order is uncertain; discuss a starting point with the mentor.",
  "journey.sourceQuestion": "What do the saved excerpts from “{name}” say about this topic? Distinguish a quotation, the stored summary, and your general explanation. What context is still missing?",
  "journey.askSource": "Discuss this source",
  "journey.exampleSaved": "Saved as a helpful example ✓",
  "journey.helped": "This helped me",
  "journey.examplesHint": "Choose “This helped me” on a mentor message. Only your confirmation saves an example for future conversations. You can edit or remove it.",
  "journey.examples": "Examples that helped",
  "journey.remove": "Remove",
  "journey.edit": "Edit",
  "journey.cancel": "Cancel",
  "journey.editExample": "Edit example",
  "journey.original": "Original mentor message",
  "journey.corrected": "edited by you",
  "journey.message": "Message {n}",
  "journey.loading": "Loading learning direction…",
  "journey.retry": "Try again",
  "journey.loadError": "Your learning direction could not be loaded.",
  "journey.save": "Save",
  "journey.planHint": "Choose one or more topics (Cmd/Ctrl for multiple). With no selection, we use the topics from your chosen source. Saved prerequisites come first; you can request new topics in the conversation.",
  "journey.topics": "Topics for this goal",
  "journey.noSource": "No specific source",
  "journey.source": "Source (optional)",
  "journey.goalPlaceholder": "For example: understand how this paper uses attention in a model",
  "journey.goalQuestion": "What would you like to understand?",
  "journey.newGoal": "New learning goal or question",
  "journey.resume": "Resume",
  "journey.completed": "completed",
  "journey.paused": "paused",
  "journey.saved": "Saved learning goals",
  "journey.reviewHint": "A short check keeps it fresh. Optional: nothing is lost if you skip it.",
  "journey.review": "Due today",
  "journey.dueStrengthen": "Shown {days} days ago · streak {streak}",
  "journey.duePractice": "Needed practice {days} days ago",
  "journey.quickCheck": "Quick check",
  "journey.dueNone": "Nothing due. Learn something new, or come back tomorrow.",
  "journey.fromConversation": "Your conversation is ready to continue.",
  "journey.fromMemory": "Continue from your saved memory.",
  "journey.recent": "Last conversation",
  "journey.direction": "My learning direction",
  "journey.finish": "Complete goal",
  "journey.pause": "Pause goal",
  "journey.stepDone": "Done",
  "journey.doneHint": "Check a step when you want to move on. This does not change your self-assessment or evidence of understanding.",
  "journey.route": "View learning route",
  "journey.continue": "Continue learning",
  "journey.chosen": "You chose this as part of your learning goal.",
  "journey.prerequisite": "Saved prerequisite for {name}.",
  "journey.next": "Next step",
  "journey.goal": "My learning goal",
  "journey.course": "My course",
  "journey.courseHint": "Made from your learning roadmap. Steps are ticked when you mark them done.",
  "tree.connectionsPrompt": "Which prerequisites and related topics would help me understand this concept? Suggest up to three specific concepts, explain why each matters and whether it is truly a prerequisite or just related, and recommend where to begin. I will choose which proposals to explore or save.",
  "tree.connections": "Suggest connections",
  "explore.listHint": "The same concepts as the map, in an accessible list. Search above filters this list too.",
  "explore.listView": "List view",
  "memory.previousSummary": "Earlier recap (before your correction)",
  "memory.intent": "Learning intent",
  "memory.selfAssessment": "My understanding",
  "memory.unrated": "Not assessed",
  "memory.not_yet": "Not yet",
  "memory.partial": "Partly",
  "memory.understood": "Understood",
  "memory.interested": "Interested",
  "memory.queued": "Plan to learn",
  "memory.learning": "Learning now",
  "memory.selfNotEvidence": "Your assessment, not demonstrated evidence",
  "memory.unknownDate": "Date not recorded",
  "memory.discussed": "Discussed",
  "memory.evidence": "Demonstrated understanding",
  "memory.evidenceHint": "Specific examples assessed by the mentor, not a mastery score.",
  "memory.noEvidence": "No conversation evidence yet. A short optional check can help.",
  "memory.openQuestions": "Open difficulties",
  "memory.history": "Observation history",
  "memory.active": "Active",
  "memory.resolved": "Resolved",
  "memory.superseded": "Retired",
  "memory.learnerCorrection": "Your correction",
  "memory.legacy": "Earlier memory; no message evidence",
  "memory.conversation": "From conversation",
  "memory.sources": "Supporting messages",
  "memory.resolve": "No longer a difficulty",
  "memory.dismiss": "This observation is incorrect",
  "memory.reactivate": "Relevant again",
  "memory.explain": "Explain",
  "memory.apply": "Apply",
  "memory.connect": "Connect",
  "memory.demonstrated": "Demonstrated in this example",
  "memory.needs_practice": "Needs practice",
  "memory.message": "Message {n}",
  "memory.recall": "Recall",
  "memory.assisted": "Solved with help",
  "memory.exercise": "Lesson exercise",
  "memory.exerciseHint": "Checked by Trellis, not by the lesson page.",
  "memory.failed": "Memory could not be updated. Your messages are saved.",
  "memory.retry": "Retry memory update",

  "cluster.nextHint": "Continue with a topic in this cluster you have not yet marked understood.",
  "cluster.startLabel": "Start this cluster",
  "cluster.beginWith": "Start with {name}",
  "cluster.prerequisiteHint": "This is an uncompleted prerequisite on the path to {name}.",
  "cluster.hubHint": "Begin with the main topic, then explore its connections with your mentor.",
  "cluster.reviewHint": "You have marked this path understood. Start with a refresher.",
  "cluster.review": "Review with mentor",
  "cluster.start": "Start learning",
  "lesson.startTitle": "Let’s begin",
  "lesson.startHint": "Start with a guided explanation at your selected depth. Then explore examples and follow-up questions together—or ask your own question below.",
  "lesson.start": "Start lesson",

  "learn.messagePlaceholder": "Ask your mentor…",
  "tree.parts": "Contains",
  "nav.label": "Workspace",
  "nav.explore": "Explore",
  "nav.learn": "Learn",
  "learn.depth": "Depth",
  "depth.1": "First steps",
  "depth.2": "Foundations",
  "depth.3": "Practical",
  "depth.4": "Technical",
  "depth.5": "Advanced",
  "learn.freshStart": "Start with what you want to understand.",
  "learn.viewMemory": "View memory",
  "learn.context": "In context",
  "learn.notes": "Learning notes",
  "learn.conceptDetails": "Concept details",
  "learn.morePaths": "More paths · {n}",
  "learn.savedPaths": "Saved & explored · {n}",
  "journey.helpedHint": "Saves this answer for this topic. The mentor reuses it when you come back here.",
  "learn.nextTopic": "Next topic",
  "learn.nextTopicHint": "Next in your learning path",
  "legend.title": "Legend",
  "graph.twoFingers": "Use two fingers to move or zoom the map",
  "learn.sessionMenu": "Conversation options",
  "learn.visualRequest": "Show this visually",
  "visual.dot": "Dot product",
  "explore.preview": "Concept preview",
  "explore.selected": "Selected concept",
  "explore.continue": "Continue learning",
  "explore.route": "A learning order",
  "explore.routeHint": "Based on prerequisite links in your map. Parallel branches can be explored independently.",
  "explore.cycle": "These prerequisite links form a loop. Review the connections before following a learning order.",
  "explore.noRoute": "No prerequisite path recorded yet. Start here and discover what you need along the way.",
  "explore.topics": "Topics",
  "explore.allTopics": "All topics",
  "explore.around": "Around {name}",
  "explore.browse": "Browse concepts",
  "explore.map": "Knowledge map. Use arrow keys to pan, plus and minus to zoom.",
  "explore.focusGroup": "Explore group {name}",
  "explore.conceptCount": "{n} concepts",
  "explore.empty": "Your curiosity starts the map",
  "explore.emptyHint": "Add a topic or a source you want to understand.",
  "explore.edgeNoReason": "This relationship is recorded in your map; no explanation was saved.",
  "explore.resume": "Continue: {name}",
  "explore.resumeAction": "Resume",
  "zoom.overview": "Topic overview",
  "zoom.overviewHint": "Main topics are named; their immediate connections appear as dots. Zoom in to reveal more.",
  "zoom.concepts": "Concepts",
  "zoom.conceptsHint": "More topic names are visible; the next level stays as dots. Hover a dot to identify it.",
  "zoom.relations": "Detailed neighborhood",
  "zoom.relationsHint": "Names unfold as you zoom. The next level stays unlabelled; select a node to inspect its connections.",
  "zoom.in": "Zoom in",
  "zoom.out": "Zoom out",
  "zoom.fit": "Fit",
  "relation.PREREQUISITE_OF": "prerequisite for",
  "relation.PART_OF": "part of",
  "relation.RELATED_TO": "related to",
  "status.learned": "Marked understood",
  "status.learning": "Learning",
  "status.queued": "Saved for later",
  "status.suggested": "Suggested",
  "profile.motion": "Map movement",
  "profile.motionLabel": "Ambient motion",
  "profile.motionHint": "Nodes drift gently and lean toward your cursor. Switch off for a still map.",
  "profile.motionReduced": "Your device requests reduced motion, so animation is paused. Your preference is saved.",

  "trail.label": "Your learning path",
  "trail.return": "Return to {name}",
  "suggestions.title": "Paths to explore",
  "suggestions.about": "About this concept",
  "suggestions.explore": "Explore",
  "suggestions.save": "Save for later",
  "suggestions.dismiss": "Dismiss",
  "suggestions.revisit": "Open conversation",
  "suggestions.queued": "Saved for later",
  "suggestions.explored": "Explored",
  "suggestions.saved": "Saved {name} to your map",
  "cmd.placeholder": "Search your knowledge…",
  "cmd.add": "Add",
  "cmd.inMap": "In your map",
  "cmd.candidates": "Candidates from the last analysis",
  "cmd.notSaved": "not saved yet",
  "cmd.learnNew": "Learn ‘{q}’ as a new concept",
  "cmd.learnAgain": "Or learn ‘{q}’ again",
  "cmd.learnThis": "Learn this",
  "cmd.noMatch": "Nothing found in your map.",
  "cmd.type.topic": "Topic",
  "cmd.type.transcript": "Transcript",
  "cmd.type.youtube": "YouTube",
  "cmd.type.paper": "Paper/text",
  "cmd.type.file": "File",
  "cmd.type.link": "Link",
  "cmd.file": "PDF, audio or text file",
  "cmd.fileTitlePh": "Title (optional; the file name otherwise)",
  "cmd.fileHint": "PDF up to 30 MB, audio up to 25 MB (an hour of mono 32 kbps mp3). Audio is transcribed by your model provider; a long episode costs a few cents and takes a few minutes.",
  "cmd.link": "Web address of an article, a PDF, or a podcast feed (RSS)",
  "cmd.linkHint": "The page text is fetched and read. A podcast feed shows its episodes first.",
  "cmd.listEpisodes": "Show episodes",
  "cmd.episodeHint": "Pick one episode. It is downloaded and transcribed before you review the candidates.",
  "cmd.topic.term": "Topic",
  "cmd.topic.termPh": "e.g. self-attention",
  "cmd.topic.context": "Context (optional)",
  "cmd.topic.contextPh": "Where did you run into this, or what exactly do you want to understand?",
  "cmd.topic.learn": "Learn",
  "cmd.topic.generate": "Generate a source on this topic",
  "cmd.topic.generateHint": "Let the model write source material and extract candidates from it",
  "cmd.paste.transcript": "Paste the transcript here. Timecodes and chapter titles are recognised.",
  "cmd.paste.paper": "Paste the text of the paper or article here.",
  "cmd.title": "Title",
  "cmd.titlePh": "Where is this from?",
  "cmd.sourceType": "Type",
  "cmd.url": "URL (optional)",
  "cmd.youtubeUrl": "YouTube URL",
  "cmd.analyze": "Analyze",
  "cmd.chars": "{n} characters · nothing saved yet",
  "cmd.close": "Close",
  "cmd.clear": "Clear",
  "cmd.searchLabel": "Search",
  "src.podcast": "podcast", "src.youtube": "youtube", "src.paper": "paper", "src.artikel": "article", "src.tekst": "text",

  "busy.analyze": "Analyzing ‘{title}’",
  "busy.analyzeHint": "The transcript is read in parts — long sources can take a few minutes",
  "busy.file": "Reading {name}",
  "busy.fileHint": "PDF pages or audio are turned into text first, then read in parts",
  "busy.url": "Fetching the page",
  "busy.urlHint": "The article text is fetched, then read in parts",
  "busy.podcast": "Transcribing {title}",
  "busy.podcastHint": "Downloading the episode and transcribing it with your model: a few minutes for an hour of audio",
  "busy.youtube": "Analyzing YouTube transcript",
  "busy.youtubeHint": "Fetching the transcript and reading it in parts — long videos can take a few minutes",
  "busy.topic": "Writing a source on ‘{topic}’",
  "busy.topicHint": "The model writes source material first and extracts candidates from it",
  "busy.learn": "Learning ‘{concept}’",
  "busy.learnHint": "Your mentor is preparing an explanation — usually 10 to 30 seconds",
  "busy.part": " part {done} of {total}",
  "busy.segment": " splitting into parts",
  "busy.merge": " merging",
  "busy.relations": " linking relations",
  "busy.fetch": " fetching transcript",

  "empty.hint": "Start with a concept you want to understand, or paste a transcript.",

  "toast.candidatesShown": "{shown} of {total} candidates shown from ‘{title}’",
  "toast.candidatesAll": "{total} candidates from ‘{title}’",
  "toast.candidatesLeft": "{left} candidates left from ‘{title}’",
  "toast.showAll": "Show all",
  "toast.hideSide": "Hide side paths",
  "toast.none": "No concepts found in ‘{title}’.",
  "toast.sourceExpired": "Source expired — analyze again.",
  "toast.retry": "Retry",
  "toast.ended": "Conversation ended and folded into your memory.",
  "toast.endedPlain": "Conversation ended.",
  "toast.rebuilt": "Memory rebuilt from {sessions} session(s), {done} processed.",
  "toast.langSaved": "Language saved: {lang}",

  "ghost.learn": "Learn this",
  "ghost.level": "level {n}",
  "ghost.busy": "Working…",
  "ghost.parts": "in {n} of {m} parts",
  "ghost.moreCtx": "+ context",
  "ghost.lessCtx": "− context",
  "ghost.importance": "Importance in this source: {n}/5",
  "ghost.candidate": "candidate, not saved yet",

  "panel.level": "Level",
  "panel.explain": "Explain",
  "panel.explainLevel": "· level {n}",
  "panel.explainTitle": "Let the mentor explain it and determine the prerequisites",
  "panel.thinking": "Thinking…",
  "panel.thinkingHint": "usually 10 to 30 seconds",
  "panel.markLearned": "Mark as understood",
  "panel.learned": "Understood ✓",
  "panel.expand": "Mentor in full screen",
  "panel.collapse": "Back to the side panel",
  "panel.close": "Close",
  "panel.defTitle": "Click for the full definition",
  "panel.sources": "Sources",
  "panel.noSources": "Not linked to a source.",
  "panel.jumpTo": "Jump to {ts}",
  "panel.source": "source",
  "panel.progress": "Progress",
  "panel.concept": "Concept",
  "panel.tree": "In your tree",
  "panel.mentor": "Mentor: {name}",

  "memo.title": "Where we left off",
  "memo.noSummary": "No summary yet.",
  "memo.quiz": "Check questions: {ok} correct, {wrong} wrong.",
  "memo.covered": "Covered ✓",
  "memo.struggles": "Struggling with",
  "memo.misconceptions": "Misconceptions",
  "memo.removeTitle": "Remove — will not come back on consolidation",
  "memo.remove": "Remove: {item}",

  "tree.here": "you are here",
  "tree.buildsOn": "builds on",
  "tree.leadsTo": "leads to",
  "tree.related": "related",
  "tree.empty": "No connections have been saved for this topic yet. Ask the mentor which prerequisites and related topics could help.",

  "progress.of": "{done} of {total} aspects covered",
  "progress.none": "No aspects discussed yet.",
  "progress.noneHint": "The mentor names them during the conversation.",

  "chat.none": "No conversation about {concept} yet.",
  "chat.noneHint": "Ask a question or pick a starting point below.",
  "chat.suggestedHint": "This is suggested prerequisite knowledge. Click",
  "chat.suggestedHint2": "to start, or just ask a question.",
  "chat.thinking": "Thinking it through — usually 10 to 30 seconds",
  "chat.placeholder": "Ask your mentor… (Enter sends, Shift+Enter for a new line)",
  "chat.send": "Send",
  "chat.end": "End conversation",
  "chat.ending": "Saving…",
  "chat.endTitle": "End the conversation and fold it into your memory",
  "chat.new": "New conversation",
  "chat.newTitle": "Start a new session; the current one is processed first",
  "chat.chip1": "Explain it simpler",
  "chat.chip2": "Give an example",
  "chat.chip3": "Quiz me",
  "chat.chip4": "Why does this matter?",
  "chat.chip5": "What am I missing?",
  "chat.levelRequest": "Please explain it again at level {n}.",
  "chat.aria": "Message to the mentor",

  "menu.profile": "My profile",
  "menu.rebuild": "Rebuild memory",
  "menu.rebuildConfirm": "Rebuild memory from saved conversation checkpoints? Your corrections and evidence will be kept.",
  "menu.rebuildYes": "Yes, rebuild",
  "menu.cancel": "Cancel",
  "menu.busy": "Working…",
  "menu.language": "Language",
  "menu.aria": "Profile menu",
  "legend.learning": "learning — in progress",
  "legend.learned": "learned — understood",
  "legend.suggested": "suggested — proposed by the mentor as prerequisite",

  "profile.title": "My profile",
  "profile.sub": "What the mentor has noticed about your learning style",
  "profile.updated": " — updated {when}",
  "profile.loading": "Loading…",
  "profile.worksWell": "Works well",
  "profile.worksWellHint": "approaches that demonstrably helped",
  "profile.worksPoorly": "Doesn't work",
  "profile.worksPoorlyHint": "approaches that didn't land",
  "profile.preferences": "Preferences",
  "profile.preferencesHint": "what you said yourself",
  "profile.nothing": "Nothing noticed yet.",
  "profile.notes": "Notes",
  "profile.save": "Save",
  "profile.language": "Language of the interface and the mentor",
  "profile.languageHint": "the mentor replies in the language of your message; your memory is written in this language",
  "profile.states": "Understanding per concept",
  "profile.concepts": "{n} concept(s)",
  "profile.noSessions": "No conversations yet.",
  "profile.noSummary": "No summary yet.",
  "profile.stats": "{covered} covered · {struggles} struggles · {mis} misconception(s) · quiz {ok}/{total}",
  "profile.manual": " · manually edited",
  "profile.rebuilt": "Rebuilt from {sessions} session(s), {done} processed.",

  "review.title": "Candidates from the analysis",
  "review.count": "{n} candidates",
  "review.parts": "{n} parts",
  "review.all": "Select all",
  "review.mains": "Main topics only",
  "review.none": "None",
  "review.loose": "Loose topics",
  "review.empty": "No candidates found.",
  "review.existing": "already in your map",
  "review.link": "link to source",
  "review.linkTitle": "Already exists: only adds the source with quotes and timecodes",
  "review.selected": "{n} selected",
  "review.commit": "Add to my map",
  "review.committing": "Adding…",
  "toast.committed": "{created} added to your map, {linked} linked, {rels} relations created.",
  "legend.queued": "To learn",
  "legend.queuedTitle": "queued — taken from a source, not learned yet",
  "common.close": "Close",
  "common.level": "Level",
  // Interactive lessons (/teach integration)
  "teach.title": "Interactive lesson",
  "teach.changeGoal": "Change goal",
  "teach.setGoal": "Set your goal for this topic",
  "teach.goal": "Your goal",
  "teach.q.intent": "What do you want from this topic?",
  "teach.q.familiarity": "How familiar is it?",
  "teach.q.approach": "How should we approach it?",
  "teach.q.minutes": "How much time today?",
  "teach.q.free": "Anything to add? (optional)",
  "teach.intent.understand": "Understand",
  "teach.intent.apply": "Apply",
  "teach.intent.build": "Build",
  "teach.intent.explore": "Explore",
  "teach.familiarity.new": "New to me",
  "teach.familiarity.basics": "Know the basics",
  "teach.familiarity.using": "Already using it",
  "teach.approach.concepts": "Concepts",
  "teach.approach.examples": "Examples",
  "teach.approach.hands_on": "Hands-on",
  "teach.approach.mix": "A mix",
  "teach.minutes": "{n} min",
  "teach.previewGoal": "Preview my goal",
  "teach.useDefaults": "Use my defaults",
  "teach.skip": "Skip",
  "teach.back": "Back",
  "teach.previewHint": "Your teacher drafted this goal from your answers. Change it until it is yours, then confirm. Nothing is saved before that.",
  "teach.confirmGoal": "This is my goal, make my lesson",
  "teach.make": "Make me a lesson",
  "teach.makeWithoutGoal": "Make a lesson without a goal",
  "teach.notePlaceholder": "Anything specific? (optional)",
  "teach.continue": "Continue",
  "teach.open": "Open the lesson",
  "teach.makeAnother": "Make another lesson",
  "lesson.talkTitle": "Or talk it through",
  "learn.sidePanel": "Mentor & context",
  "lesson.talkHint": "Ask anything about this topic. The mentor knows your study guide and your lesson.",
  "lesson.talk": "Explain it to me",
  "teach.retry": "Try again",
  "teach.cancel": "Cancel",
  "teach.stage.queued": "Waiting",
  "teach.stage.preparing": "Reading what you know",
  "teach.stage.generating": "Writing the lesson",
  "teach.stage.validating": "Testing the lesson",
  "teach.progressHint": "This takes one to three minutes. You can keep talking to your mentor below.",
  "teach.failed": "The lesson could not be made this time. Your mentor is still here below.",
  "teach.cancelled": "Cancelled.",
  "teach.more": "{lessons} lessons · {references} references",
  "teach.cards": "Reference cards · {references}",
  "teach.syllabus": "Your lessons on this topic",
  "teach.block.done": "Done",
  "teach.block.open": "In progress",
  "teach.block.new": "Not started",
  "teach.review": "Review",
  "teach.start": "Start",
  "teach.nextBlock": "Next block",
  "teach.nextBlockHint": "The teacher writes it from what you have shown so far: one outcome, practice, feedback.",
  "teach.recommended": "Recommended topic",
  "teach.recAccept": "Explore it",
  "teach.recDismiss": "Dismiss",
  "teach.proposal": "Your teacher proposes a new goal:",
  "teach.proposalReview": "Review it",
  "teach.kind.summary": "Summary",
  "teach.kind.procedure": "Procedure",
  "teach.kind.example": "Worked example",
  "teach.kind.formula": "Formula",
  "teach.kind.glossary": "Glossary",
  "teach.tabLesson": "Lesson",
  "teach.tabStudy": "Study",
  "study.title": "Study guide",
  "study.loading": "Opening your study guide…",
  "study.writing": "Writing your study guide",
  "study.writingHint": "One complete chapter at your chosen depth, from your own sources. About a minute; it is kept for next time.",
  "study.practice": "Practise with an interactive lesson",
  "study.ask": "Ask the mentor",
  "study.rewrite": "Rewrite this guide",
  "teach.tabMentor": "Mentor",
  "teach.pause": "Pause lesson",
  "teach.loading": "Opening the lesson…",
  "teach.loadFailed": "The lesson could not be opened. Your mentor is still here.",
  "teach.stopped": "The lesson was stopped because it tried to leave its sandbox. Your progress is saved.",
  "teach.completed": "Lesson done. Your answers are saved.",
  "teach.backToTopic": "Back to the topic",
  "teach.offline": "Offline: changes are saved when you are back",
  "teach.notSaved": "Not saved yet, retrying…",
  "teach.askAbout": "Ask about this",
  "teach.askReference": "I have a question about the reference \"{title}\".",
  "teach.close": "Close",
  "teach.repairing": "The phone test found a problem. Your teacher is fixing it (round {n}).",
  "teach.failedTest": "The lesson did not pass its own test, so it was not shown to you. Your mentor is still here below.",
  "teach.failedCostLimit": "Your cost limit of ${usd} per lesson was reached before the lesson passed its checks. Raise or turn off the limit in My profile → Settings → Lesson costs, then try again.",
  "teach.failedBudget": "Making the lesson took too long, so it was stopped. Your mentor is still here below; try again in a moment.",
  "teach.failedSetup": "Trellis cannot check lessons right now: the lesson checker is not set up correctly. Nothing was spent. The server log says what to fix.",
  "teach.phoneNote": "Made on a computer: some parts of this lesson may not work well on a phone.",
  "teach.kept.title": "Your lesson is made, but it did not pass every check:",
  "teach.kept.fix": "Fix these",
  "teach.kept.open": "Open it anyway",
  "teach.kept.startOver": "Start over",
  "teach.kept.hint": "Fix these: the AI continues from this lesson and fixes only these problems, for fewer tokens than a new lesson. Open it anyway: free, but some parts may not work.",
  "teach.kept.cannotOpen": "This lesson cannot be opened as it is. Fix these continues from it, for fewer tokens than a new lesson.",
  "teach.kept.fixing": "Fixing the kept lesson: only the problems listed before.",
  "teach.issueSteps": "step {steps}",
  "teach.openedWithIssues": "Opened without passing every check: some parts may not work as intended.",
  "teach.issue.unknown_block": "It links to a building block that does not exist",
  "teach.issue.unsafe_code": "It uses code that is not allowed in a lesson",
  "teach.issue.slow_start": "It took too long to start",
  "teach.issue.did_not_load": "It did not open",
  "teach.issue.script_error": "Part of it shows an error",
  "teach.issue.contrast": "Some text is hard to read",
  "teach.issue.small_button": "A button is too small to tap on a phone",
  "teach.issue.sideways": "Something is too wide for a phone screen",
  "teach.issue.several_at_once": "A phone shows several parts at once",
  "teach.issue.network": "It tried to load something from the internet (blocked)",
  "teach.issue.missing_part": "A part of the lesson is missing",
  "teach.issue.incomplete": "The goal or the 'ask your mentor' hint is missing",
  "teach.issue.sources": "A source link is not right",
  "teach.issue.language": "Part of it is in the wrong language",
  "teach.issue.too_little_text": "It has almost no text",
  "teach.issue.description": "Its description file is incomplete",
  "teach.issue.other": "Another check failed",
  "gate.welcomeBack": "Welcome back",
  "gate.who": "Who are you?",
  "gate.password": "Password",
  "gate.login": "Log in",
  "gate.wrongPassword": "Wrong password.",
  "gate.tooMany": "Too many attempts. Wait ten minutes.",
  "gate.noServer": "The Trellis server did not answer, so your password was not checked. Wait a moment and try again.",
  "gate.forgot": "Forgot it? The owner of this install resets it: see the README, 'Reset a password'.",
  "gate.setupTitle": "Welcome to Trellis",
  "gate.setupLead": "Three short steps: your name, the AI model you want to use, and a password. Nothing is saved before the last step.",
  "gate.name": "Your name",
  "gate.nameHint": "The mentor uses it. You can change it later.",
  "gate.language": "Interface language",
  "gate.languageHint": "The mentor answers in the language you write in.",
  "gate.next": "Next",
  "gate.back": "Back",
  "gate.modelTitle": "Choose your AI model",
  "gate.modelLead": "Trellis talks to a model provider with your own key. You pay the provider directly; Trellis itself is free.",
  "gate.modelFromEnv": "A model is already configured in the server settings. You can keep it or pick another one.",
  "gate.keepEnv": "Keep the server settings",
  "gate.provider": "Provider",
  "gate.getKey": "Get a key",
  "gate.key": "API key",
  "gate.keyHint": "Stored on your own server only. Trellis never sends it anywhere except to the provider.",
  "gate.embedProvider": "Embedding provider",
  "gate.embedHint": "This provider has no embedding model. Embeddings place concepts on the map. The choice is fixed for this database.",
  "gate.embedKey": "API key for embeddings",
  "gate.custom": "Other (any LiteLLM model)",
  "gate.presetHint": "A provider picks the three models for you and fixes the embedding size. Pick Other to type your own.",
  "gate.customHint": "Type LiteLLM model ids: the provider prefix, a slash, and the model name. One key is used for all three models.",
  "gate.customList": "List of providers",
  "gate.mentorModel": "Mentor model",
  "gate.extractModel": "Extract model",
  "gate.extractHint": "A fast, cheap model. It pulls concepts out of your conversations.",
  "gate.embedModel": "Embedding model",
  "gate.embedDim": "Embedding size",
  "gate.embedDimHint": "The number of values per embedding, from the model's documentation. It is fixed for this database.",
  "gate.keyEnv": "Key variable",
  "gate.keyEnvHint": "The name LiteLLM reads the key from. Leave it empty for a local model without a key.",
  "gate.costNote": "Typical cost: a few cents per conversation, about $0.50 per interactive lesson. Every lesson job records its token use.",
  "gate.passwordTitle": "Set a password",
  "gate.passwordLead": "Trellis is your private notebook. This password is the only door.",
  "gate.passwordHint": "At least 8 characters. Use a password manager.",
  "gate.repeat": "Repeat the password",
  "gate.finish": "Finish setup",
  "menu.logout": "Log out",
  "profile.account": "Account",
  "profile.accountHint": "Logged in as {name}. This browser stays logged in for 30 days.",
  "explore.viewLabel": "Explore view",
  "explore.graph": "Graph",
  "explore.path": "Learning path",
  "import.running": "Analysis is running. Long videos can take a few minutes; the topics will appear here when ready.",
  "import.elapsed": "elapsed",
  "import.youtubeFailed": "Automatic retrieval failed. If YouTube offers Show transcript, copy its text and paste it here.",
  "import.pasteTranscript": "Paste a transcript instead",
  "import.transcriptHint": "On YouTube, expand the video description and look for Show transcript. Copy the transcript, including timestamps if available, and paste it here.",
  "import.analyzing": "Analyzing…",
  "translation.retry": "Show translation",
  "translation.show": "Show translation",
  "translation.original": "Translated · Original",
  "costs.title": "Lesson costs, last 30 days",
  "costs.headline": "{lessons} lessons · about ${usd}",
  "costs.tokens": "{total} tokens, of which {cached} from cache · model {model}",
  "costs.disclaimer": "Estimate at ${inp} / ${out} per million input / output tokens. Your provider's bill is the truth; set TEACH_PRICE_IN and TEACH_PRICE_OUT in .env to correct the prices.",
  "costs.limit": "Limit per lesson",
  "costs.limitOff": "Off",
  "costs.limitOffHint": "No limit. Each lesson uses what it needs.",
  "costs.limitOnHint": "Near ${usd}, the author stops adding new parts and publishes what passed its checks. A lesson can go a little over. If nothing passed yet, no lesson is made.",
  "backup.title": "Backups",
  "backup.hint": "A backup is made every night at {hour}:10 UTC; the last {keep} are kept in the backups folder next to the app. A backup holds your whole graph and your lesson files.",
  "backup.unavailable": "The backups folder is not mounted, so no backups are made. See the README, 'Backups'.",
  "backup.makeNow": "Make a backup now",
  "backup.made": "Backup made: {nodes} nodes in {seconds} s.",
  "backup.verify": "Verify",
  "backup.verified": "Readable, {n} lesson file(s) match.",
  "backup.broken": "This backup is incomplete.",
  "backup.restoreHint": "Restoring replaces everything. On the machine that runs Trellis:",
};
export default en;
