const en = {
  "home.nextAction": "Choose your next step",
"video.provenance":"AI video analysis \u00b7 paraphrases, not verified captions. Timestamps are approximate.",
"video.approximate":"Approximate \u00b7 AI video analysis",
"busy.video":"Analyzing video directly",

  "profile.simpleIntro": "Settings and how you like to learn.",
  "profile.tab.settings": "Settings",
  "profile.tab.teaching": "Teaching preferences",
  "profile.tab.memory": "Memory",
  "profile.languageSafe": "New explanations and memory updates use your preferred language. Existing conversations are preserved; the mentor can also use memory written in another language.",
  "profile.yourChoices": "Your choices",
  "profile.choicesHint": "Select the approaches you prefer. Blue pills are your choices; you can change them anytime.",
  "profile.custom": "Add your own preference",
  "profile.addPreference": "Add",
  "profile.mentorNotes": "Observations from conversations",
  "profile.mentorNotesHint": "Purple pills are observations recorded by the mentor, including earlier memory. They may depend on the topic. Your explicit choices and current request take priority. Remove anything that does not fit.",
  "profile.choice.0": "Step by step",
  "profile.choice.1": "Concrete examples",
  "profile.choice.2": "Code examples",
  "profile.choice.3": "Visual diagrams",
  "profile.choice.4": "Analogies",
  "profile.choice.5": "Short explanations",
  "profile.choice.6": "Technical depth",
  "profile.choice.7": "Optional practice questions",

  "home.yourLearning": "Your learning space",
  "home.otherTopic": "Another topic",
  "home.start": "What would you like to explore?",
  "home.startHint": "Choose a topic on the map or search above. Your conversations and learning goals will be here when you return.",
  "home.chooseTopic": "Choose a topic",
  "home.currentRecent": "Current topic · last conversation",
  "search.browse": "Search and explore",
  "search.topics": "Topics",
  "search.clusters": "Clusters",
  "search.hint": "Type to search, choose a topic, or explore a cluster.",
  "search.resultsHint": "Choose a result to open it.",
  "search.count": "{n} topics",
  "search.noClusters": "No matching clusters.",
  "search.clearCluster": "Clear cluster {name}",

  "journey.reviewRequest": "Can we briefly revisit this topic? Give me one short application question; I’ll decide whether I want to try it.",
  "journey.reviewStart": "Try a short review",
  "journey.cycle": "This route contains a prerequisite cycle. The order is uncertain; discuss a starting point with the mentor.",
  "journey.sourceQuestion": "What do the saved excerpts from “{name}” say about this topic? Distinguish a quotation, the stored summary, and your general explanation. What context is still missing?",
  "journey.askSource": "Discuss this source",
  "journey.exampleSaved": "Saved as a helpful example ✓",
  "journey.helped": "This helped me",
  "journey.examplesHint": "Choose “This helped me” on a mentor message. Only your confirmation saves an example for future conversations. You can edit or remove it.",
  "journey.examples": "Examples that helped",
  "journey.remove": "Remove",
  "journey.edit": "Edit",
  "journey.cancel": "Cancel",
  "journey.editExample": "Edit example",
  "journey.original": "Original mentor message",
  "journey.corrected": "edited by you",
  "journey.message": "Message {n}",
  "journey.loading": "Loading learning direction…",
  "journey.retry": "Try again",
  "journey.loadError": "Your learning direction could not be loaded.",
  "journey.save": "Save",
  "journey.planHint": "Choose one or more topics (Cmd/Ctrl for multiple). With no selection, we use the topics from your chosen source. Saved prerequisites come first; you can request new topics in the conversation.",
  "journey.topics": "Topics for this goal",
  "journey.noSource": "No specific source",
  "journey.source": "Source (optional)",
  "journey.goalPlaceholder": "For example: understand how this paper uses attention in a model",
  "journey.goalQuestion": "What would you like to understand?",
  "journey.newGoal": "New learning goal or question",
  "journey.resume": "Resume",
  "journey.completed": "completed",
  "journey.paused": "paused",
  "journey.saved": "Saved learning goals",
  "journey.reviewHint": "You demonstrated this at least two weeks ago. That does not mean you have forgotten it. Reviewing is optional.",
  "journey.review": "Revisit something?",
  "journey.fromConversation": "Your conversation is ready to continue.",
  "journey.fromMemory": "Continue from your saved memory.",
  "journey.recent": "Last conversation",
  "journey.direction": "My learning direction",
  "journey.finish": "Complete goal",
  "journey.pause": "Pause goal",
  "journey.stepDone": "Done",
  "journey.doneHint": "Check a step when you want to move on. This does not change your self-assessment or evidence of understanding.",
  "journey.route": "View learning route",
  "journey.continue": "Continue learning",
  "journey.chosen": "You chose this as part of your learning goal.",
  "journey.prerequisite": "Saved prerequisite for {name}.",
  "journey.next": "Next step",
  "journey.goal": "My learning goal",
  "tree.connectionsPrompt": "Which prerequisites and related topics would help me understand this concept? Suggest up to three specific concepts, explain why each matters and whether it is truly a prerequisite or just related, and recommend where to begin. I will choose which proposals to explore or save.",
  "tree.connections": "Suggest connections",
  "explore.listHint": "The same concepts as the map, in an accessible list. Search above filters this list too.",
  "explore.listView": "List view",
  "memory.previousSummary": "Earlier recap (before your correction)",
  "memory.intent": "Learning intent",
  "memory.selfAssessment": "My understanding",
  "memory.unrated": "Not assessed",
  "memory.not_yet": "Not yet",
  "memory.partial": "Partly",
  "memory.understood": "Understood",
  "memory.interested": "Interested",
  "memory.queued": "Plan to learn",
  "memory.learning": "Learning now",
  "memory.selfNotEvidence": "Your assessment, not demonstrated evidence",
  "memory.unknownDate": "Date not recorded",
  "memory.discussed": "Discussed",
  "memory.evidence": "Demonstrated understanding",
  "memory.evidenceHint": "Specific examples assessed by the mentor, not a mastery score.",
  "memory.noEvidence": "No conversation evidence yet. A short optional check can help.",
  "memory.openQuestions": "Open difficulties",
  "memory.history": "Observation history",
  "memory.active": "Active",
  "memory.resolved": "Resolved",
  "memory.superseded": "Retired",
  "memory.learnerCorrection": "Your correction",
  "memory.legacy": "Earlier memory; no message evidence",
  "memory.conversation": "From conversation",
  "memory.sources": "Supporting messages",
  "memory.resolve": "No longer a difficulty",
  "memory.dismiss": "This observation is incorrect",
  "memory.reactivate": "Relevant again",
  "memory.explain": "Explain",
  "memory.apply": "Apply",
  "memory.connect": "Connect",
  "memory.demonstrated": "Demonstrated in this example",
  "memory.needs_practice": "Needs practice",
  "memory.message": "Message {n}",
  "memory.failed": "Memory could not be updated. Your messages are saved.",
  "memory.retry": "Retry memory update",

  "cluster.nextHint": "Continue with a topic in this cluster you have not yet marked understood.",
  "cluster.startLabel": "Start this cluster",
  "cluster.beginWith": "Start with {name}",
  "cluster.prerequisiteHint": "This is an uncompleted prerequisite on the path to {name}.",
  "cluster.hubHint": "Begin with the main topic, then explore its connections with your mentor.",
  "cluster.reviewHint": "You have marked this path understood. Start with a refresher.",
  "cluster.review": "Review with mentor",
  "cluster.start": "Start learning",
  "lesson.startTitle": "Let’s begin",
  "lesson.startHint": "Start with a guided explanation at your selected depth. Then explore examples and follow-up questions together—or ask your own question below.",
  "lesson.start": "Start lesson",

  "learn.messagePlaceholder": "Ask your mentor…",
  "tree.parts": "Contains",
  "nav.label": "Workspace",
  "nav.explore": "Explore",
  "nav.learn": "Learn",
  "learn.depth": "Depth",
  "depth.1": "First steps",
  "depth.2": "Foundations",
  "depth.3": "Practical",
  "depth.4": "Technical",
  "depth.5": "Advanced",
  "learn.freshStart": "Start with what you want to understand.",
  "learn.viewMemory": "View memory",
  "learn.context": "In context",
  "learn.notes": "Learning notes",
  "learn.conceptDetails": "Concept details",
  "learn.morePaths": "More paths · {n}",
  "learn.savedPaths": "Saved & explored · {n}",
  "journey.helpedHint": "Saves this answer for this topic. The mentor reuses it when you come back here.",
  "learn.nextTopic": "Next topic",
  "learn.nextTopicHint": "Next in your learning path",
  "legend.title": "Legend",
  "graph.twoFingers": "Use two fingers to move or zoom the map",
  "learn.sessionMenu": "Conversation options",
  "learn.visualRequest": "Show this visually",
  "visual.dot": "Dot product",
  "explore.preview": "Concept preview",
  "explore.selected": "Selected concept",
  "explore.continue": "Continue learning",
  "explore.route": "A learning order",
  "explore.routeHint": "Based on prerequisite links in your map. Parallel branches can be explored independently.",
  "explore.cycle": "These prerequisite links form a loop. Review the connections before following a learning order.",
  "explore.noRoute": "No prerequisite path recorded yet. Start here and discover what you need along the way.",
  "explore.topics": "Topics",
  "explore.allTopics": "All topics",
  "explore.around": "Around {name}",
  "explore.browse": "Browse concepts",
  "explore.map": "Knowledge map. Use arrow keys to pan, plus and minus to zoom.",
  "explore.focusGroup": "Explore group {name}",
  "explore.conceptCount": "{n} concepts",
  "explore.empty": "Your curiosity starts the map",
  "explore.emptyHint": "Add a topic or a source you want to understand.",
  "explore.edgeNoReason": "This relationship is recorded in your map; no explanation was saved.",
  "explore.resume": "Continue: {name}",
  "explore.resumeAction": "Resume",
  "zoom.overview": "Topic overview",
  "zoom.overviewHint": "Main topics are named; their immediate connections appear as dots. Zoom in to reveal more.",
  "zoom.concepts": "Concepts",
  "zoom.conceptsHint": "More topic names are visible; the next level stays as dots. Hover a dot to identify it.",
  "zoom.relations": "Detailed neighborhood",
  "zoom.relationsHint": "Names unfold as you zoom. The next level stays unlabelled; select a node to inspect its connections.",
  "zoom.in": "Zoom in",
  "zoom.out": "Zoom out",
  "zoom.fit": "Fit",
  "relation.PREREQUISITE_OF": "prerequisite for",
  "relation.PART_OF": "part of",
  "relation.RELATED_TO": "related to",
  "status.learned": "Marked understood",
  "status.learning": "Learning",
  "status.queued": "Saved for later",
  "status.suggested": "Suggested",
  "profile.motion": "Map movement",
  "profile.motionLabel": "Ambient motion",
  "profile.motionHint": "Nodes drift gently and lean toward your cursor. Switch off for a still map.",
  "profile.motionReduced": "Your device requests reduced motion, so animation is paused. Your preference is saved.",

  "trail.label": "Your learning path",
  "trail.return": "Return to {name}",
  "suggestions.title": "Paths to explore",
  "suggestions.about": "About this concept",
  "suggestions.explore": "Explore",
  "suggestions.save": "Save for later",
  "suggestions.dismiss": "Dismiss",
  "suggestions.revisit": "Open conversation",
  "suggestions.queued": "Saved for later",
  "suggestions.explored": "Explored",
  "suggestions.saved": "Saved {name} to your map",
  "cmd.placeholder": "Search your knowledge…",
  "cmd.add": "Add",
  "cmd.inMap": "In your map",
  "cmd.candidates": "Candidates from the last analysis",
  "cmd.notSaved": "not saved yet",
  "cmd.learnNew": "Learn ‘{q}’ as a new concept",
  "cmd.learnAgain": "Or learn ‘{q}’ again",
  "cmd.learnThis": "Learn this",
  "cmd.noMatch": "Nothing found in your map.",
  "cmd.type.topic": "Topic",
  "cmd.type.transcript": "Transcript",
  "cmd.type.youtube": "YouTube",
  "cmd.type.paper": "Paper/text",
  "cmd.topic.term": "Topic",
  "cmd.topic.termPh": "e.g. self-attention",
  "cmd.topic.context": "Context (optional)",
  "cmd.topic.contextPh": "Where did you run into this, or what exactly do you want to understand?",
  "cmd.topic.learn": "Learn",
  "cmd.topic.generate": "Generate a source on this topic",
  "cmd.topic.generateHint": "Let the model write source material and extract candidates from it",
  "cmd.paste.transcript": "Paste the transcript here. Timecodes and chapter titles are recognised.",
  "cmd.paste.paper": "Paste the text of the paper or article here.",
  "cmd.title": "Title",
  "cmd.titlePh": "Where is this from?",
  "cmd.sourceType": "Type",
  "cmd.url": "URL (optional)",
  "cmd.youtubeUrl": "YouTube URL",
  "cmd.analyze": "Analyze",
  "cmd.chars": "{n} characters · nothing saved yet",
  "cmd.close": "Close",
  "cmd.clear": "Clear",
  "cmd.searchLabel": "Search",
  "src.podcast": "podcast", "src.youtube": "youtube", "src.paper": "paper", "src.artikel": "article", "src.tekst": "text",

  "busy.analyze": "Analyzing ‘{title}’",
  "busy.analyzeHint": "The transcript is read in parts — long sources can take a few minutes",
  "busy.youtube": "Analyzing YouTube transcript",
  "busy.youtubeHint": "Fetching the transcript and reading it in parts — long videos can take a few minutes",
  "busy.topic": "Writing a source on ‘{topic}’",
  "busy.topicHint": "The model writes source material first and extracts candidates from it",
  "busy.learn": "Learning ‘{concept}’",
  "busy.learnHint": "Your mentor is preparing an explanation — usually 10 to 30 seconds",
  "busy.part": " part {done} of {total}",
  "busy.segment": " splitting into parts",
  "busy.merge": " merging",
  "busy.relations": " linking relations",
  "busy.fetch": " fetching transcript",

  "empty.hint": "Start with a concept you want to understand, or paste a transcript.",

  "toast.candidatesShown": "{shown} of {total} candidates shown from ‘{title}’",
  "toast.candidatesAll": "{total} candidates from ‘{title}’",
  "toast.candidatesLeft": "{left} candidates left from ‘{title}’",
  "toast.showAll": "Show all",
  "toast.hideSide": "Hide side paths",
  "toast.none": "No concepts found in ‘{title}’.",
  "toast.sourceExpired": "Source expired — analyze again.",
  "toast.retry": "Retry",
  "toast.ended": "Conversation ended and folded into your memory.",
  "toast.endedPlain": "Conversation ended.",
  "toast.rebuilt": "Memory rebuilt from {sessions} session(s), {done} processed.",
  "toast.langSaved": "Language saved: {lang}",

  "ghost.learn": "Learn this",
  "ghost.level": "level {n}",
  "ghost.busy": "Working…",
  "ghost.parts": "in {n} of {m} parts",
  "ghost.moreCtx": "+ context",
  "ghost.lessCtx": "− context",
  "ghost.importance": "Importance in this source: {n}/5",
  "ghost.candidate": "candidate, not saved yet",

  "panel.level": "Level",
  "panel.explain": "Explain",
  "panel.explainLevel": "· level {n}",
  "panel.explainTitle": "Let the mentor explain it and determine the prerequisites",
  "panel.thinking": "Thinking…",
  "panel.thinkingHint": "usually 10 to 30 seconds",
  "panel.markLearned": "Mark as understood",
  "panel.learned": "Understood ✓",
  "panel.expand": "Mentor in full screen",
  "panel.collapse": "Back to the side panel",
  "panel.close": "Close",
  "panel.defTitle": "Click for the full definition",
  "panel.sources": "Sources",
  "panel.noSources": "Not linked to a source.",
  "panel.jumpTo": "Jump to {ts}",
  "panel.source": "source",
  "panel.progress": "Progress",
  "panel.concept": "Concept",
  "panel.tree": "In your tree",
  "panel.mentor": "Mentor: {name}",

  "memo.title": "Where we left off",
  "memo.noSummary": "No summary yet.",
  "memo.quiz": "Check questions: {ok} correct, {wrong} wrong.",
  "memo.covered": "Covered ✓",
  "memo.struggles": "Struggling with",
  "memo.misconceptions": "Misconceptions",
  "memo.removeTitle": "Remove — will not come back on consolidation",
  "memo.remove": "Remove: {item}",

  "tree.here": "you are here",
  "tree.buildsOn": "builds on",
  "tree.leadsTo": "leads to",
  "tree.related": "related",
  "tree.empty": "No connections have been saved for this topic yet. Ask the mentor which prerequisites and related topics could help.",

  "progress.of": "{done} of {total} aspects covered",
  "progress.none": "No aspects discussed yet.",
  "progress.noneHint": "The mentor names them during the conversation.",

  "chat.none": "No conversation about {concept} yet.",
  "chat.noneHint": "Ask a question or pick a starting point below.",
  "chat.suggestedHint": "This is suggested prerequisite knowledge. Click",
  "chat.suggestedHint2": "to start, or just ask a question.",
  "chat.thinking": "Thinking it through — usually 10 to 30 seconds",
  "chat.placeholder": "Ask your mentor… (Enter sends, Shift+Enter for a new line)",
  "chat.send": "Send",
  "chat.end": "End conversation",
  "chat.ending": "Saving…",
  "chat.endTitle": "End the conversation and fold it into your memory",
  "chat.new": "New conversation",
  "chat.newTitle": "Start a new session; the current one is processed first",
  "chat.chip1": "Explain it simpler",
  "chat.chip2": "Give an example",
  "chat.chip3": "Quiz me",
  "chat.chip4": "Why does this matter?",
  "chat.chip5": "What am I missing?",
  "chat.levelRequest": "Please explain it again at level {n}.",
  "chat.aria": "Message to the mentor",

  "menu.profile": "My profile",
  "menu.rebuild": "Rebuild memory",
  "menu.rebuildConfirm": "Rebuild memory from saved conversation checkpoints? Your corrections and evidence will be kept.",
  "menu.rebuildYes": "Yes, rebuild",
  "menu.cancel": "Cancel",
  "menu.busy": "Working…",
  "menu.language": "Language",
  "menu.aria": "Profile menu",
  "legend.learning": "learning — in progress",
  "legend.learned": "learned — understood",
  "legend.suggested": "suggested — proposed by the mentor as prerequisite",

  "profile.title": "My profile",
  "profile.sub": "What the mentor has noticed about your learning style",
  "profile.updated": " — updated {when}",
  "profile.loading": "Loading…",
  "profile.worksWell": "Works well",
  "profile.worksWellHint": "approaches that demonstrably helped",
  "profile.worksPoorly": "Doesn't work",
  "profile.worksPoorlyHint": "approaches that didn't land",
  "profile.preferences": "Preferences",
  "profile.preferencesHint": "what you said yourself",
  "profile.nothing": "Nothing noticed yet.",
  "profile.notes": "Notes",
  "profile.save": "Save",
  "profile.language": "Language of the interface and the mentor",
  "profile.languageHint": "the mentor replies in the language of your message; your memory is written in this language",
  "profile.states": "Understanding per concept",
  "profile.concepts": "{n} concept(s)",
  "profile.noSessions": "No conversations yet.",
  "profile.noSummary": "No summary yet.",
  "profile.stats": "{covered} covered · {struggles} struggles · {mis} misconception(s) · quiz {ok}/{total}",
  "profile.manual": " · manually edited",
  "profile.rebuilt": "Rebuilt from {sessions} session(s), {done} processed.",

  "review.title": "Candidates from the analysis",
  "review.count": "{n} candidates",
  "review.parts": "{n} parts",
  "review.all": "Select all",
  "review.mains": "Main topics only",
  "review.none": "None",
  "review.loose": "Loose topics",
  "review.empty": "No candidates found.",
  "review.existing": "already in your map",
  "review.link": "link to source",
  "review.linkTitle": "Already exists: only adds the source with quotes and timecodes",
  "review.selected": "{n} selected",
  "review.commit": "Add to my map",
  "review.committing": "Adding…",
  "toast.committed": "{created} added to your map, {linked} linked, {rels} relations created.",
  "legend.queued": "To learn",
  "legend.queuedTitle": "queued — taken from a source, not learned yet",
  "common.close": "Close",
  "common.level": "Level",
  // Interactive lessons (/teach integration)
  "teach.title": "Interactive lesson",
  "teach.changeGoal": "Change goal",
  "teach.setGoal": "Set your goal for this topic",
  "teach.goal": "Your goal",
  "teach.q.intent": "What do you want from this topic?",
  "teach.q.familiarity": "How familiar is it?",
  "teach.q.approach": "How should we approach it?",
  "teach.q.minutes": "How much time today?",
  "teach.q.free": "Anything to add? (optional)",
  "teach.intent.understand": "Understand",
  "teach.intent.apply": "Apply",
  "teach.intent.build": "Build",
  "teach.intent.explore": "Explore",
  "teach.familiarity.new": "New to me",
  "teach.familiarity.basics": "Know the basics",
  "teach.familiarity.using": "Already using it",
  "teach.approach.concepts": "Concepts",
  "teach.approach.examples": "Examples",
  "teach.approach.hands_on": "Hands-on",
  "teach.approach.mix": "A mix",
  "teach.minutes": "{n} min",
  "teach.previewGoal": "Preview my goal",
  "teach.useDefaults": "Use my defaults",
  "teach.skip": "Skip",
  "teach.back": "Back",
  "teach.previewHint": "Your teacher drafted this goal from your answers. Change it until it is yours, then confirm. Nothing is saved before that.",
  "teach.confirmGoal": "This is my goal",
  "teach.make": "Make me a lesson",
  "teach.makeWithoutGoal": "Make a lesson without a goal",
  "teach.notePlaceholder": "Anything specific? (optional)",
  "teach.continue": "Continue",
  "teach.open": "Open the lesson",
  "teach.retry": "Try again",
  "teach.cancel": "Cancel",
  "teach.stage.queued": "Waiting",
  "teach.stage.preparing": "Reading what you know",
  "teach.stage.generating": "Writing the lesson",
  "teach.stage.validating": "Testing it on a phone",
  "teach.progressHint": "This takes one to three minutes. You can keep talking to your mentor below.",
  "teach.failed": "The lesson could not be made this time. Your mentor is still here below.",
  "teach.cancelled": "Cancelled.",
  "teach.more": "{lessons} lessons · {references} references",
  "teach.recommended": "Recommended topic",
  "teach.recAccept": "Explore it",
  "teach.recDismiss": "Dismiss",
  "teach.proposal": "Your teacher proposes a new goal:",
  "teach.proposalReview": "Review it",
  "teach.kind.summary": "Summary",
  "teach.kind.procedure": "Procedure",
  "teach.kind.example": "Worked example",
  "teach.kind.formula": "Formula",
  "teach.kind.glossary": "Glossary",
  "teach.tabLesson": "Lesson",
  "teach.tabMentor": "Mentor",
  "teach.pause": "Pause lesson",
  "teach.loading": "Opening the lesson…",
  "teach.loadFailed": "The lesson could not be opened. Your mentor is still here.",
  "teach.stopped": "The lesson was stopped because it tried to leave its sandbox. Your progress is saved.",
  "teach.completed": "Lesson done. Your answers are saved.",
  "teach.backToTopic": "Back to the topic",
  "teach.offline": "Offline: changes are saved when you are back",
  "teach.notSaved": "Not saved yet, retrying…",
  "teach.askAbout": "Ask about this",
  "teach.askReference": "I have a question about the reference \"{title}\".",
  "teach.close": "Close",
  "teach.repairing": "The phone test found a problem. Your teacher is fixing it (round {n}).",
  "teach.failedTest": "The lesson did not pass its own test, so it was not shown to you. Your mentor is still here below.",
};
export default en;
