const nl = {
  "home.nextAction": "Kies je volgende stap",
"video.provenance":"AI-videoanalyse \u00b7 parafrases, geen geverifieerde ondertiteling. Tijdcodes zijn bij benadering.",
"video.approximate":"Bij benadering \u00b7 AI-videoanalyse",
"busy.video":"Video rechtstreeks analyseren",

  "profile.simpleIntro": "Instellingen en hoe je graag leert.",
  "profile.tab.settings": "Instellingen",
  "profile.tab.teaching": "Leervoorkeuren",
  "profile.tab.memory": "Geheugen",
  "profile.languageSafe": "Nieuwe uitleg en geheugenupdates gebruiken je voorkeurstaal. Bestaande gesprekken blijven behouden; de mentor kan ook anderstalig geheugen gebruiken.",
  "profile.yourChoices": "Jouw keuzes",
  "profile.choicesHint": "Selecteer de aanpak die je prettig vindt. Blauwe pillen zijn jouw keuzes; je kunt ze altijd wijzigen.",
  "profile.custom": "Voeg een eigen voorkeur toe",
  "profile.addPreference": "Toevoegen",
  "profile.mentorNotes": "Opmerkingen uit gesprekken",
  "profile.mentorNotesHint": "Paarse pillen zijn door de mentor vastgelegde observaties, inclusief eerder geheugen. Ze kunnen afhangen van het onderwerp. Je eigen keuzes en actuele vraag hebben voorrang. Verwijder wat niet klopt.",
  "profile.choice.0": "Stap voor stap",
  "profile.choice.1": "Concrete voorbeelden",
  "profile.choice.2": "Codevoorbeelden",
  "profile.choice.3": "Visuele diagrammen",
  "profile.choice.4": "Analogieën",
  "profile.choice.5": "Korte uitleg",
  "profile.choice.6": "Technische diepgang",
  "profile.choice.7": "Vrijwillige oefenvragen",

  "home.yourLearning": "Jouw leerplek",
  "home.otherTopic": "Ander onderwerp",
  "home.start": "Wat wil je ontdekken?",
  "home.startHint": "Kies een onderwerp op de kaart of zoek hierboven. Hier vind je straks je gesprekken en leerdoelen terug.",
  "home.chooseTopic": "Kies een onderwerp",
  "home.currentRecent": "Huidig onderwerp · laatste gesprek",
  "search.browse": "Zoeken en verkennen",
  "search.topics": "Onderwerpen",
  "search.clusters": "Clusters",
  "search.hint": "Typ om te zoeken, kies een onderwerp of verken een cluster.",
  "search.resultsHint": "Kies een resultaat om het te openen.",
  "search.count": "{n} onderwerpen",
  "search.noClusters": "Geen passende clusters.",
  "search.clearCluster": "Cluster {name} wissen",

  "journey.reviewRequest": "Kunnen we kort terugblikken op dit onderwerp? Geef me één korte toepassingsvraag; ik kies zelf of ik die wil proberen.",
  "journey.reviewStart": "Probeer een korte terugblik",
  "journey.cycle": "Deze route bevat een kring in de voorkennisrelaties. De volgorde is onzeker; bespreek met de mentor waar je begint.",
  "journey.sourceQuestion": "Wat zeggen de opgeslagen fragmenten uit “{name}” over dit onderwerp? Maak onderscheid tussen een citaat, de opgeslagen samenvatting en jouw algemene uitleg. Welke context ontbreekt nog?",
  "journey.askSource": "Bespreek deze bron",
  "journey.exampleSaved": "Bewaard als helpend voorbeeld ✓",
  "journey.helped": "Dit hielp mij",
  "journey.examplesHint": "Klik bij een mentorbericht op “Dit hielp mij”. Alleen jouw bevestiging bewaart een voorbeeld voor volgende gesprekken. Je kunt het aanpassen of verwijderen.",
  "journey.examples": "Voorbeelden die hielpen",
  "journey.remove": "Verwijderen",
  "journey.edit": "Aanpassen",
  "journey.cancel": "Annuleren",
  "journey.editExample": "Voorbeeld aanpassen",
  "journey.original": "Oorspronkelijk mentorbericht",
  "journey.corrected": "door jou aangepast",
  "journey.message": "Bericht {n}",
  "journey.loading": "Leerrichting laden…",
  "journey.retry": "Opnieuw proberen",
  "journey.loadError": "Je leerrichting kon niet worden geladen.",
  "journey.save": "Bewaren",
  "journey.planHint": "Kies één of meer onderwerpen (Cmd/Ctrl voor meerdere). Zonder selectie gebruiken we de onderwerpen uit je gekozen bron. Bestaande voorkennis wordt eerst geplaatst; nieuwe onderwerpen kun je in het gesprek voorstellen.",
  "journey.topics": "Onderwerpen voor dit doel",
  "journey.noSource": "Zonder specifieke bron",
  "journey.source": "Bron (optioneel)",
  "journey.goalPlaceholder": "Bijvoorbeeld: begrijpen hoe deze paper aandacht in een model gebruikt",
  "journey.goalQuestion": "Wat wil je begrijpen?",
  "journey.newGoal": "Nieuw leerdoel of vraag",
  "journey.resume": "Hervatten",
  "journey.completed": "afgerond",
  "journey.paused": "gepauzeerd",
  "journey.saved": "Bewaarde leerdoelen",
  "journey.reviewHint": "Je liet dit minstens twee weken geleden zien. Dat betekent niet dat je het vergeten bent. Herhalen is optioneel.",
  "journey.dueStrengthen": "Getoond {days} dagen geleden · reeks {streak}",
  "journey.duePractice": "Oefening nodig {days} dagen geleden",
  "journey.quickCheck": "Korte check",
  "journey.dueNone": "Niets te herhalen. Leer iets nieuws, of kom morgen terug.",
  "journey.review": "Nog eens bekijken?",
  "journey.fromConversation": "Je gesprek staat voor je klaar.",
  "journey.fromMemory": "Ga verder vanuit het opgeslagen geheugen.",
  "journey.recent": "Laatste gesprek",
  "journey.direction": "Mijn leerrichting",
  "journey.finish": "Doel afronden",
  "journey.pause": "Doel pauzeren",
  "journey.stepDone": "Afgerond",
  "journey.doneHint": "Vink aan als je verder wilt. Dit verandert je zelfinschatting of bewijs van begrip niet.",
  "journey.route": "Bekijk de leerroute",
  "journey.continue": "Verder leren",
  "journey.chosen": "Door jou gekozen als onderdeel van dit leerdoel.",
  "journey.prerequisite": "Opgeslagen voorkennis voor {name}.",
  "journey.next": "Volgende stap",
  "journey.goal": "Mijn leerdoel",
  "journey.course": "Mijn cursus",
  "journey.courseHint": "Gemaakt van je leerroute. Stappen worden afgevinkt als je ze op klaar zet.",
  "tree.connectionsPrompt": "Welke voorkennis en verwante onderwerpen zouden mij helpen dit concept te begrijpen? Stel maximaal drie concrete concepten voor, met per concept waarom het relevant is en of het echt voorkennis is of alleen verwant. Geef aan waar ik het beste begin. Ik kies zelf welke voorstellen ik verken of bewaar.",
  "tree.connections": "Stel verbindingen voor",
  "explore.listHint": "Dezelfde concepten als op de kaart, als toegankelijke lijst. Zoeken hierboven filtert ook deze lijst.",
  "explore.listView": "Lijstweergave",
  "memory.previousSummary": "Eerdere samenvatting (vóór je correctie)",
  "memory.intent": "Leerintentie",
  "memory.selfAssessment": "Mijn inschatting",
  "memory.unrated": "Nog niet ingeschat",
  "memory.not_yet": "Nog niet",
  "memory.partial": "Gedeeltelijk",
  "memory.understood": "Begrepen",
  "memory.interested": "Interesse",
  "memory.queued": "Wil ik leren",
  "memory.learning": "Nu aan het leren",
  "memory.selfNotEvidence": "Jouw inschatting, geen aangetoond bewijs",
  "memory.unknownDate": "Datum niet vastgelegd",
  "memory.discussed": "Besproken",
  "memory.evidence": "Aangetoond begrip",
  "memory.evidenceHint": "Concrete voorbeelden beoordeeld door de mentor, geen beheersingsscore.",
  "memory.noEvidence": "Nog geen gespreksbewijs. Een korte vrijwillige begripcheck kan helpen.",
  "memory.openQuestions": "Open moeitepunten",
  "memory.history": "Observatiegeschiedenis",
  "memory.active": "Actief",
  "memory.resolved": "Opgelost",
  "memory.superseded": "Niet meer actueel",
  "memory.learnerCorrection": "Jouw correctie",
  "memory.legacy": "Eerder geheugen; geen berichtbewijs",
  "memory.conversation": "Uit het gesprek",
  "memory.sources": "Ondersteunende berichten",
  "memory.resolve": "Geen moeitepunt meer",
  "memory.dismiss": "Deze observatie klopt niet",
  "memory.reactivate": "Weer actueel",
  "memory.explain": "Uitleggen",
  "memory.apply": "Toepassen",
  "memory.connect": "Verband leggen",
  "memory.demonstrated": "Getoond in dit voorbeeld",
  "memory.needs_practice": "Nog oefenen",
  "memory.message": "Bericht {n}",
  "memory.recall": "Ophalen",
  "memory.assisted": "Opgelost met hulp",
  "memory.exercise": "Lesoefening",
  "memory.exerciseHint": "Gecontroleerd door Trellis, niet door de lespagina.",
  "memory.failed": "Het geheugen kon niet worden bijgewerkt. Je berichten zijn opgeslagen.",
  "memory.retry": "Geheugenupdate opnieuw proberen",

  "cluster.nextHint": "Ga verder met een onderwerp in dit cluster dat je nog niet als begrepen hebt gemarkeerd.",
  "cluster.startLabel": "Begin met dit cluster",
  "cluster.beginWith": "Begin met {name}",
  "cluster.prerequisiteHint": "Dit is nog niet afgeronde voorkennis op het pad naar {name}.",
  "cluster.hubHint": "Begin met het hoofdonderwerp en verken daarna de verbindingen met je mentor.",
  "cluster.reviewHint": "Je hebt dit pad als begrepen gemarkeerd. Begin met een opfrisser.",
  "cluster.review": "Herhaal met je mentor",
  "cluster.start": "Begin met leren",
  "lesson.startTitle": "Laten we beginnen",
  "lesson.startHint": "Begin met een uitleg op de gekozen diepgang. Verken daarna samen voorbeelden en vervolgvragen, of stel hieronder je eigen vraag.",
  "lesson.start": "Start de les",

  "learn.messagePlaceholder": "Vraag het je mentor…",
  "tree.parts": "Bevat",
  "nav.label": "Werkruimte",
  "nav.explore": "Verkennen",
  "nav.learn": "Leren",
  "learn.depth": "Diepgang",
  "depth.1": "Eerste stappen",
  "depth.2": "Basis",
  "depth.3": "Praktisch",
  "depth.4": "Technisch",
  "depth.5": "Verdiepend",
  "learn.freshStart": "Begin met wat je wilt begrijpen.",
  "learn.viewMemory": "Bekijk geheugen",
  "learn.context": "In context",
  "learn.notes": "Leernotities",
  "learn.conceptDetails": "Over het concept",
  "learn.morePaths": "Meer zijpaden · {n}",
  "learn.savedPaths": "Bewaard en verkend · {n}",
  "journey.helpedHint": "Bewaart dit antwoord bij dit onderwerp. De mentor gebruikt het opnieuw als je hier terugkomt.",
  "learn.nextTopic": "Volgend onderwerp",
  "learn.nextTopicHint": "Volgende stap in je leerpad",
  "legend.title": "Legenda",
  "graph.twoFingers": "Gebruik twee vingers om de kaart te verschuiven of te zoomen",
  "learn.sessionMenu": "Gespreksopties",
  "learn.visualRequest": "Laat dit visueel zien",
  "visual.dot": "Inproduct",
  "explore.preview": "Concept bekijken",
  "explore.selected": "Geselecteerd concept",
  "explore.continue": "Verder leren",
  "explore.route": "Een leervolgorde",
  "explore.routeHint": "Gebaseerd op voorkennisrelaties in je kaart. Losse takken kun je onafhankelijk verkennen.",
  "explore.cycle": "Deze voorkennisrelaties vormen een lus. Controleer de verbindingen voordat je een leervolgorde volgt.",
  "explore.noRoute": "Nog geen voorkennispad vastgelegd. Begin hier en ontdek onderweg wat je nodig hebt.",
  "explore.topics": "Onderwerpen",
  "explore.allTopics": "Alle onderwerpen",
  "explore.around": "Rond {name}",
  "explore.browse": "Conceptenlijst",
  "explore.map": "Kenniskaart. Gebruik pijltjestoetsen om te bewegen en plus en min om te zoomen.",
  "explore.focusGroup": "Verken groep {name}",
  "explore.conceptCount": "{n} concepten",
  "explore.empty": "Je nieuwsgierigheid begint de kaart",
  "explore.emptyHint": "Voeg een onderwerp of bron toe die je wilt begrijpen.",
  "explore.edgeNoReason": "Deze relatie staat in je kaart; er is nog geen uitleg bij bewaard.",
  "explore.resume": "Verder met: {name}",
  "explore.resumeAction": "Hervatten",
  "zoom.overview": "Onderwerpenoverzicht",
  "zoom.overviewHint": "Hoofdonderwerpen hebben namen; hun directe verbindingen zijn stippen. Zoom in voor meer detail.",
  "zoom.concepts": "Concepten",
  "zoom.conceptsHint": "Meer onderwerpen krijgen een naam; het volgende niveau blijft stippen. Wijs een stip aan voor de naam.",
  "zoom.relations": "Buurt in detail",
  "zoom.relationsHint": "Bij inzoomen verschijnen meer namen. Het volgende niveau blijft zonder labels; kies een knoop voor de verbindingen.",
  "zoom.in": "Inzoomen",
  "zoom.out": "Uitzoomen",
  "zoom.fit": "Passend",
  "relation.PREREQUISITE_OF": "voorkennis voor",
  "relation.PART_OF": "onderdeel van",
  "relation.RELATED_TO": "verwant aan",
  "status.learned": "Als begrepen gemarkeerd",
  "status.learning": "Aan het leren",
  "status.queued": "Bewaard voor later",
  "status.suggested": "Voorgesteld",
  "profile.motion": "Beweging in de kaart",
  "profile.motionLabel": "Zachte beweging",
  "profile.motionHint": "Knopen bewegen rustig en komen iets naar je cursor toe. Zet uit voor een stilstaande kaart.",
  "profile.motionReduced": "Je apparaat vraagt om minder beweging; animatie staat daarom stil. Je voorkeur is bewaard.",

  "trail.label": "Je leerpad",
  "trail.return": "Terug naar {name}",
  "suggestions.title": "Verder verkennen",
  "suggestions.about": "Over dit concept",
  "suggestions.explore": "Verkennen",
  "suggestions.save": "Bewaar voor later",
  "suggestions.dismiss": "Afwijzen",
  "suggestions.revisit": "Open gesprek",
  "suggestions.queued": "Bewaard voor later",
  "suggestions.explored": "Verkend",
  "suggestions.saved": "{name} bewaard in je kaart",
  // command bar
  "cmd.placeholder": "Zoek in je kennis…",
  "cmd.add": "Toevoegen",
  "cmd.inMap": "In je kaart",
  "cmd.candidates": "Kandidaten uit de laatste analyse",
  "cmd.notSaved": "nog niet opgeslagen",
  "cmd.learnNew": "Leer ‘{q}’ als nieuw concept",
  "cmd.learnAgain": "Of leer ‘{q}’ opnieuw",
  "cmd.learnThis": "Leer dit",
  "cmd.noMatch": "Niets gevonden in je kaart.",
  "cmd.type.topic": "Onderwerp",
  "cmd.type.transcript": "Transcript",
  "cmd.type.youtube": "YouTube",
  "cmd.type.file": "Bestand",
  "cmd.type.link": "Link",
  "cmd.file": "PDF, audio of tekstbestand",
  "cmd.fileTitlePh": "Titel (optioneel; anders de bestandsnaam)",
  "cmd.fileHint": "PDF tot 30 MB, audio tot 25 MB (een uur mono 32 kbps mp3). Audio wordt door je modelaanbieder uitgeschreven; een lange aflevering kost een paar cent en duurt enkele minuten.",
  "cmd.link": "Webadres van een artikel, een PDF of een podcastfeed (RSS)",
  "cmd.linkHint": "De paginatekst wordt opgehaald en gelezen. Een podcastfeed toont eerst de afleveringen.",
  "cmd.listEpisodes": "Toon afleveringen",
  "cmd.episodeHint": "Kies één aflevering. Die wordt gedownload en uitgeschreven voordat je de kandidaten beoordeelt.",
  "cmd.type.paper": "Paper/tekst",
  "cmd.topic.term": "Onderwerp",
  "cmd.topic.termPh": "bijv. self-attention",
  "cmd.topic.context": "Context (optioneel)",
  "cmd.topic.contextPh": "Waar kwam je dit tegen, of wat wil je er precies van begrijpen?",
  "cmd.topic.learn": "Leer",
  "cmd.topic.generate": "Genereer bron over dit onderwerp",
  "cmd.topic.generateHint": "Laat het model zelf bronmateriaal schrijven en haal daar kandidaten uit",
  "cmd.paste.transcript": "Plak hier het transcript. Tijdcodes en hoofdstuktitels worden herkend.",
  "cmd.paste.paper": "Plak hier de tekst van de paper of het artikel.",
  "cmd.title": "Titel",
  "cmd.titlePh": "Waar komt dit vandaan?",
  "cmd.sourceType": "Type",
  "cmd.url": "URL (optioneel)",
  "cmd.youtubeUrl": "YouTube-URL",
  "cmd.analyze": "Analyseer",
  "cmd.chars": "{n} tekens · nog niets opgeslagen",
  "cmd.close": "Sluiten",
  "cmd.clear": "Leegmaken",
  "cmd.searchLabel": "Zoeken",
  "src.podcast": "podcast", "src.youtube": "youtube", "src.paper": "paper", "src.artikel": "artikel", "src.tekst": "tekst",

  // busy / voortgang
  "busy.analyze": "Analyseren van ‘{title}’",
  "busy.analyzeHint": "Het transcript wordt in delen gelezen — lange bronnen kunnen enkele minuten duren",
  "busy.file": "{name} lezen",
  "busy.fileHint": "PDF-pagina's of audio worden eerst tekst, daarna in delen gelezen",
  "busy.url": "Pagina ophalen",
  "busy.urlHint": "De artikeltekst wordt opgehaald en in delen gelezen",
  "busy.podcast": "{title} uitschrijven",
  "busy.podcastHint": "De aflevering wordt gedownload en met je model uitgeschreven: enkele minuten per uur audio",
  "busy.youtube": "YouTube-transcript analyseren",
  "busy.youtubeHint": "Transcript ophalen en in delen lezen — lange video's kunnen enkele minuten duren",
  "busy.topic": "Bron schrijven over ‘{topic}’",
  "busy.topicHint": "Het model schrijft eerst bronmateriaal en haalt daar kandidaten uit",
  "busy.learn": "‘{concept}’ leren",
  "busy.learnHint": "De mentor bereidt een uitleg voor — meestal 10 tot 30 seconden",
  "busy.part": " deel {done} van {total}",
  "busy.segment": " in delen splitsen",
  "busy.merge": " samenvoegen",
  "busy.relations": " relaties leggen",
  "busy.fetch": " transcript ophalen",

  // empty state
  "empty.hint": "Begin met een concept dat je wilt begrijpen, of plak een transcript.",

  // toasts
  "toast.candidatesShown": "{shown} van {total} kandidaten getoond uit ‘{title}’",
  "toast.candidatesAll": "{total} kandidaten uit ‘{title}’",
  "toast.candidatesLeft": "{left} kandidaten over uit ‘{title}’",
  "toast.showAll": "Toon alle",
  "toast.hideSide": "Verberg zijpaden",
  "toast.none": "Geen concepten gevonden in ‘{title}’.",
  "toast.sourceExpired": "Bron verlopen — analyseer opnieuw.",
  "toast.retry": "Opnieuw",
  "toast.ended": "Gesprek afgesloten en verwerkt in je geheugen.",
  "toast.endedPlain": "Gesprek afgesloten.",
  "toast.rebuilt": "Geheugen opnieuw opgebouwd uit {sessions} sessie(s), {done} verwerkt.",
  "toast.langSaved": "Taal opgeslagen: {lang}",

  // ghost chip
  "ghost.learn": "Leer dit",
  "ghost.level": "niveau {n}",
  "ghost.busy": "Bezig…",
  "ghost.parts": "in {n} van {m} delen",
  "ghost.moreCtx": "+ context",
  "ghost.lessCtx": "− context",
  "ghost.importance": "Belang in deze bron: {n}/5",
  "ghost.candidate": "kandidaat, nog niet opgeslagen",

  // paneel
  "panel.level": "Niveau",
  "panel.explain": "Leg uit",
  "panel.explainLevel": "· niveau {n}",
  "panel.explainTitle": "Laat de mentor het uitleggen en de voorkennis bepalen",
  "panel.thinking": "Denkt na…",
  "panel.thinkingHint": "meestal 10 tot 30 seconden",
  "panel.markLearned": "Markeer als begrepen",
  "panel.learned": "Begrepen ✓",
  "panel.expand": "Mentor op volledig scherm",
  "panel.collapse": "Terug naar het zijpaneel",
  "panel.close": "Sluiten",
  "panel.defTitle": "Klik voor de volledige definitie",
  "panel.sources": "Bronnen",
  "panel.noSources": "Niet aan een bron gekoppeld.",
  "panel.jumpTo": "Spring naar {ts}",
  "panel.source": "bron",
  "panel.progress": "Voortgang",
  "panel.concept": "Concept",
  "panel.tree": "In je boom",
  "panel.mentor": "Mentor: {name}",

  // geheugen
  "memo.title": "Waar we gebleven waren",
  "memo.noSummary": "Nog geen samenvatting.",
  "memo.quiz": "Controlevragen: {ok} goed, {wrong} fout.",
  "memo.covered": "Behandeld ✓",
  "memo.struggles": "Moeite mee",
  "memo.misconceptions": "Misvattingen",
  "memo.removeTitle": "Verwijderen — komt niet terug bij consolidatie",
  "memo.remove": "Verwijder: {item}",

  // boom
  "tree.here": "je bent hier",
  "tree.buildsOn": "bouwt op",
  "tree.leadsTo": "leidt naar",
  "tree.related": "gerelateerd",
  "tree.empty": "Er zijn nog geen verbindingen opgeslagen voor dit onderwerp. Vraag de mentor welke voorkennis en verwante onderwerpen kunnen helpen.",

  // voortgang
  "progress.of": "{done} van {total} aspecten behandeld",
  "progress.none": "Nog geen aspecten besproken.",
  "progress.noneHint": "De mentor benoemt ze tijdens het gesprek.",

  // chat
  "chat.none": "Nog geen gesprek over {concept}.",
  "chat.noneHint": "Stel een vraag of kies een startpunt hieronder.",
  "chat.suggestedHint": "Dit is voorgestelde voorkennis. Klik",
  "chat.suggestedHint2": "om ermee te beginnen, of stel meteen een vraag.",
  "chat.thinking": "Denkt na — meestal 10 tot 30 seconden",
  "chat.placeholder": "Vraag je mentor… (Enter verstuurt, Shift+Enter voor een nieuwe regel)",
  "chat.send": "Stuur",
  "chat.end": "Beëindig gesprek",
  "chat.ending": "Opslaan…",
  "chat.endTitle": "Sluit het gesprek af en verwerk het in je geheugen",
  "chat.new": "Nieuw gesprek",
  "chat.newTitle": "Begin een nieuwe sessie; de huidige wordt eerst verwerkt",
  "chat.chip1": "Leg eenvoudiger uit",
  "chat.chip2": "Geef een voorbeeld",
  "chat.chip3": "Overhoor mij",
  "chat.chip4": "Waarom is dit belangrijk?",
  "chat.chip5": "Wat mis ik nog?",
  "chat.levelRequest": "Leg het opnieuw uit op niveau {n}, alsjeblieft.",
  "chat.aria": "Bericht aan de mentor",

  // linksonder
  "menu.profile": "Mijn profiel",
  "menu.rebuild": "Geheugen opnieuw opbouwen",
  "menu.rebuildConfirm": "Geheugen opnieuw opbouwen uit opgeslagen gesprekscheckpoints? Je correcties en bewijs blijven behouden.",
  "menu.rebuildYes": "Ja, herbouw",
  "menu.cancel": "Annuleer",
  "menu.busy": "Bezig…",
  "menu.language": "Taal",
  "menu.aria": "Profielmenu",
  "legend.learning": "learning — mee bezig",
  "legend.learned": "learned — begrepen",
  "legend.suggested": "suggested — door de mentor voorgesteld als voorkennis",

  // profiel
  "profile.title": "Mijn profiel",
  "profile.sub": "Wat de mentor over je leerstijl heeft opgemerkt",
  "profile.updated": " — bijgewerkt {when}",
  "profile.loading": "Laden…",
  "profile.worksWell": "Werkt goed",
  "profile.worksWellHint": "aanpak die aantoonbaar hielp",
  "profile.worksPoorly": "Werkt niet",
  "profile.worksPoorlyHint": "aanpak die niet landde",
  "profile.preferences": "Voorkeuren",
  "profile.preferencesHint": "wat je zelf hebt aangegeven",
  "profile.nothing": "Nog niets opgemerkt.",
  "profile.notes": "Notities",
  "profile.save": "Opslaan",
  "profile.language": "Taal van de interface en de mentor",
  "profile.languageHint": "de mentor antwoordt in de taal van je bericht; je geheugen wordt in deze taal geschreven",
  "profile.states": "Begripstoestand per concept",
  "profile.concepts": "{n} concept(en)",
  "profile.noSessions": "Nog geen gesprekken gevoerd.",
  "profile.noSummary": "Nog geen samenvatting.",
  "profile.stats": "{covered} behandeld · {struggles} moeite · {mis} misvatting(en) · quiz {ok}/{total}",
  "profile.manual": " · handmatig aangepast",
  "profile.rebuilt": "Opnieuw opgebouwd uit {sessions} sessie(s), {done} verwerkt.",

  "review.title": "Kandidaten uit de analyse",
  "review.count": "{n} kandidaten",
  "review.parts": "{n} delen",
  "review.all": "Alles selecteren",
  "review.mains": "Alleen hoofdtopics",
  "review.none": "Niets",
  "review.loose": "Losse onderwerpen",
  "review.empty": "Geen kandidaten gevonden.",
  "review.existing": "al in je kaart",
  "review.link": "koppel aan bron",
  "review.linkTitle": "Bestaat al: voegt alleen de bron met citaten en tijdcodes toe",
  "review.selected": "{n} geselecteerd",
  "review.commit": "Voeg toe aan mijn kaart",
  "review.committing": "Toevoegen…",
  "toast.committed": "{created} toegevoegd aan je kaart, {linked} gekoppeld, {rels} relaties gelegd.",
  "legend.queued": "Te leren",
  "legend.queuedTitle": "queued — opgenomen uit een bron, nog niet geleerd",
  // algemeen
  "common.close": "Sluiten",
  "common.level": "Niveau",
  // Interactive lessons (/teach integration)
  "teach.title": "Interactieve les",
  "teach.changeGoal": "Doel aanpassen",
  "teach.setGoal": "Bepaal je doel voor dit onderwerp",
  "teach.goal": "Je doel",
  "teach.q.intent": "Wat wil je met dit onderwerp?",
  "teach.q.familiarity": "Hoe bekend is het?",
  "teach.q.approach": "Hoe pakken we het aan?",
  "teach.q.minutes": "Hoeveel tijd heb je vandaag?",
  "teach.q.free": "Nog iets toe te voegen? (optioneel)",
  "teach.intent.understand": "Begrijpen",
  "teach.intent.apply": "Toepassen",
  "teach.intent.build": "Bouwen",
  "teach.intent.explore": "Verkennen",
  "teach.familiarity.new": "Nieuw voor mij",
  "teach.familiarity.basics": "Ik ken de basis",
  "teach.familiarity.using": "Ik gebruik het al",
  "teach.approach.concepts": "Concepten",
  "teach.approach.examples": "Voorbeelden",
  "teach.approach.hands_on": "Zelf doen",
  "teach.approach.mix": "Een mix",
  "teach.minutes": "{n} min",
  "teach.previewGoal": "Bekijk mijn doel",
  "teach.useDefaults": "Gebruik mijn standaard",
  "teach.skip": "Overslaan",
  "teach.back": "Terug",
  "teach.previewHint": "Je docent heeft dit doel gemaakt uit je antwoorden. Pas het aan tot het van jou is en bevestig dan. Tot die tijd wordt er niets opgeslagen.",
  "teach.confirmGoal": "Dit is mijn doel, maak mijn les",
  "teach.make": "Maak een les voor mij",
  "teach.makeWithoutGoal": "Maak een les zonder doel",
  "teach.notePlaceholder": "Iets specifieks? (optioneel)",
  "teach.continue": "Ga verder",
  "teach.makeAnother": "Nog een les maken",
  "learn.sidePanel": "Mentor & context",
  "lesson.talkTitle": "Of bespreek het",
  "lesson.talkHint": "Vraag alles over dit onderwerp. De mentor kent je studiegids en je les.",
  "lesson.talk": "Leg het me uit",
  "teach.open": "Open de les",
  "teach.retry": "Opnieuw proberen",
  "teach.cancel": "Annuleren",
  "teach.stage.queued": "Wachten",
  "teach.stage.preparing": "Lezen wat je al weet",
  "teach.stage.generating": "De les schrijven",
  "teach.stage.validating": "De les testen",
  "teach.progressHint": "Dit duurt één tot drie minuten. Je kunt hieronder gewoon met je mentor verder praten.",
  "teach.failed": "De les kon deze keer niet gemaakt worden. Je mentor is er hieronder nog gewoon.",
  "teach.cancelled": "Geannuleerd.",
  "teach.cards": "Naslagkaarten · {references}",
  "teach.syllabus": "Je lessen over dit onderwerp",
  "teach.block.done": "Klaar",
  "teach.block.open": "Bezig",
  "teach.block.new": "Nog niet begonnen",
  "teach.review": "Herhalen",
  "teach.start": "Begin",
  "teach.nextBlock": "Volgend blok",
  "teach.nextBlockHint": "De leraar schrijft het op basis van wat je tot nu toe hebt laten zien: één doel, oefening, feedback.",
  "teach.more": "{lessons} lessen · {references} naslag",
  "teach.recommended": "Aanbevolen onderwerp",
  "teach.recAccept": "Verkennen",
  "teach.recDismiss": "Negeren",
  "teach.proposal": "Je docent stelt een nieuw doel voor:",
  "teach.proposalReview": "Bekijken",
  "teach.kind.summary": "Samenvatting",
  "teach.kind.procedure": "Stappenplan",
  "teach.kind.example": "Uitgewerkt voorbeeld",
  "teach.kind.formula": "Formule",
  "teach.kind.glossary": "Woordenlijst",
  "teach.tabStudy": "Studeren",
  "study.title": "Studiegids",
  "study.loading": "Je studiegids openen…",
  "study.writing": "Je studiegids wordt geschreven",
  "study.writingHint": "Eén volledig hoofdstuk op de gekozen diepgang, uit je eigen bronnen. Ongeveer een minuut; hij wordt bewaard.",
  "study.practice": "Oefen met een interactieve les",
  "study.ask": "Vraag de mentor",
  "study.rewrite": "Deze gids herschrijven",
  "teach.tabLesson": "Les",
  "teach.tabMentor": "Mentor",
  "teach.pause": "Les pauzeren",
  "teach.loading": "De les wordt geopend…",
  "teach.loadFailed": "De les kon niet geopend worden. Je mentor is er nog gewoon.",
  "teach.stopped": "De les is gestopt omdat hij uit zijn zandbak probeerde te komen. Je voortgang is bewaard.",
  "teach.completed": "Les klaar. Je antwoorden zijn bewaard.",
  "teach.backToTopic": "Terug naar het onderwerp",
  "teach.offline": "Offline: wijzigingen worden bewaard zodra je terug bent",
  "teach.notSaved": "Nog niet bewaard, nieuwe poging…",
  "teach.askAbout": "Stel hier een vraag over",
  "teach.askReference": "Ik heb een vraag over de naslag \"{title}\".",
  "teach.close": "Sluiten",
  "teach.repairing": "De telefoontest vond een probleem. Je docent lost het op (ronde {n}).",
  "teach.failedTest": "De les kwam niet door zijn eigen test en is je daarom niet getoond. Je mentor is er hieronder nog gewoon.",
  "teach.failedCostLimit": "Je kostenlimiet van ${usd} per les was bereikt voordat de les door zijn controles kwam. Verhoog of zet de limiet uit in Mijn profiel → Instellingen → Leskosten en probeer het opnieuw.",
  "teach.failedBudget": "Het maken van de les duurde te lang en is gestopt. Je mentor is er hieronder nog gewoon; probeer het zo opnieuw.",
  "gate.welcomeBack": "Welkom terug",
  "gate.who": "Wie ben je?",
  "gate.password": "Wachtwoord",
  "gate.login": "Inloggen",
  "gate.wrongPassword": "Verkeerd wachtwoord.",
  "gate.tooMany": "Te veel pogingen. Wacht tien minuten.",
  "gate.noServer": "De Trellis-server gaf geen antwoord, dus je wachtwoord is niet gecontroleerd. Wacht even en probeer het opnieuw.",
  "gate.forgot": "Vergeten? De eigenaar van deze installatie zet het terug: zie de README, 'Reset a password'.",
  "gate.setupTitle": "Welkom bij Trellis",
  "gate.setupLead": "Drie korte stappen: je naam, het AI-model dat je wilt gebruiken, en een wachtwoord. Er wordt niets opgeslagen vóór de laatste stap.",
  "gate.name": "Je naam",
  "gate.nameHint": "De mentor gebruikt hem. Later aan te passen.",
  "gate.language": "Taal van de app",
  "gate.languageHint": "De mentor antwoordt in de taal waarin je schrijft.",
  "gate.next": "Verder",
  "gate.back": "Terug",
  "gate.modelTitle": "Kies je AI-model",
  "gate.modelLead": "Trellis praat met een modelaanbieder via je eigen sleutel. Je betaalt de aanbieder rechtstreeks; Trellis zelf is gratis.",
  "gate.modelFromEnv": "Er is al een model ingesteld in de serverinstellingen. Je kunt dat houden of een ander kiezen.",
  "gate.keepEnv": "Serverinstellingen houden",
  "gate.provider": "Aanbieder",
  "gate.getKey": "Sleutel aanvragen",
  "gate.key": "API-sleutel",
  "gate.keyHint": "Alleen op je eigen server opgeslagen. Trellis stuurt hem nergens heen behalve naar de aanbieder.",
  "gate.embedProvider": "Aanbieder voor embeddings",
  "gate.embedHint": "Deze aanbieder heeft geen embedding-model. Embeddings plaatsen concepten op de kaart. De keuze ligt vast voor deze database.",
  "gate.embedKey": "API-sleutel voor embeddings",
  "gate.custom": "Anders (elk LiteLLM-model)",
  "gate.presetHint": "Een aanbieder kiest de drie modellen voor je en legt de embedding-grootte vast. Kies Anders om ze zelf in te typen.",
  "gate.customHint": "Typ LiteLLM-model-id's: het voorvoegsel van de aanbieder, een schuine streep en de modelnaam. Eén sleutel geldt voor alle drie de modellen.",
  "gate.customList": "Lijst van aanbieders",
  "gate.mentorModel": "Mentormodel",
  "gate.extractModel": "Extractiemodel",
  "gate.extractHint": "Een snel, goedkoop model. Het haalt concepten uit je gesprekken.",
  "gate.embedModel": "Embedding-model",
  "gate.embedDim": "Embedding-grootte",
  "gate.embedDimHint": "Het aantal waarden per embedding, uit de documentatie van het model. Ligt vast voor deze database.",
  "gate.keyEnv": "Sleutelvariabele",
  "gate.keyEnvHint": "De naam waaronder LiteLLM de sleutel leest. Laat leeg voor een lokaal model zonder sleutel.",
  "gate.costNote": "Gebruikelijke kosten: een paar cent per gesprek, ongeveer $0,50 per interactieve les. Elke lesopdracht registreert zijn tokengebruik.",
  "gate.passwordTitle": "Kies een wachtwoord",
  "gate.passwordLead": "Trellis is je privé-notitieboek. Dit wachtwoord is de enige deur.",
  "gate.passwordHint": "Minstens 8 tekens. Gebruik een wachtwoordmanager.",
  "gate.repeat": "Herhaal het wachtwoord",
  "gate.finish": "Installatie afronden",
  "menu.logout": "Uitloggen",
  "profile.account": "Account",
  "profile.accountHint": "Ingelogd als {name}. Deze browser blijft 30 dagen ingelogd.",
  "explore.viewLabel": "Verkenweergave",
  "explore.graph": "Kenniskaart",
  "explore.path": "Leerpad",
  "import.running": "De analyse loopt. Lange video's kunnen een paar minuten duren; de onderwerpen verschijnen hier zodra ze klaar zijn.",
  "import.elapsed": "verstreken",
  "import.youtubeFailed": "Automatisch ophalen mislukte. Biedt YouTube 'Transcript weergeven', kopieer die tekst dan en plak hem hier.",
  "import.pasteTranscript": "Plak in plaats daarvan een transcript",
  "import.transcriptHint": "Klap op YouTube de videobeschrijving uit en zoek 'Transcript weergeven'. Kopieer het transcript, met tijdcodes als die er zijn, en plak het hier.",
  "import.analyzing": "Analyseren…",
  "translation.retry": "Vertaling tonen",
  "translation.show": "Toon vertaling",
  "translation.original": "Vertaald · Origineel",
  "costs.title": "Leskosten, laatste 30 dagen",
  "costs.headline": "{lessons} lessen · ongeveer ${usd}",
  "costs.tokens": "{total} tokens, waarvan {cached} uit cache · model {model}",
  "costs.disclaimer": "Schatting bij ${inp} / ${out} per miljoen invoer- / uitvoertokens. De rekening van je aanbieder is de waarheid; zet TEACH_PRICE_IN en TEACH_PRICE_OUT in .env om de prijzen te corrigeren.",
  "costs.limit": "Limiet per les",
  "costs.limitOff": "Uit",
  "costs.limitOffHint": "Geen limiet. Elke les gebruikt wat hij nodig heeft.",
  "costs.limitOnHint": "Rond ${usd} stopt de auteur met nieuwe onderdelen en publiceert wat door de controles kwam. Een les kan er iets overheen gaan. Als nog niets door de controles kwam, wordt er geen les gemaakt.",
  "backup.title": "Back-ups",
  "backup.hint": "Elke nacht om {hour}:10 UTC wordt een back-up gemaakt; de laatste {keep} blijven staan in de map backups naast de app. Een back-up bevat je hele graaf en je lesbestanden.",
  "backup.unavailable": "De map backups is niet gekoppeld, dus er worden geen back-ups gemaakt. Zie de README, 'Backups'.",
  "backup.makeNow": "Nu een back-up maken",
  "backup.made": "Back-up gemaakt: {nodes} knopen in {seconds} s.",
  "backup.verify": "Controleren",
  "backup.verified": "Leesbaar, {n} lesbestand(en) kloppen.",
  "backup.broken": "Deze back-up is onvolledig.",
  "backup.restoreHint": "Terugzetten vervangt alles. Op de machine waar Trellis draait:",
};
export default nl;
